### ISSUE TITLE
on creating note file, insert description as first line

### ISSUE THREAD

**Issue by linuxcaffe** [blakesweeney/unite-taskwarrior#10]
Hit "o" and you're editing a note file.. but what was that about again? 
On first creating a new note file, having the task description inserted as the first line of the file, would make that note file function a lot more obvious.

**Comment by blakesweeney** [comment]
This should be possible now. In addition, I added a little configuration option to allow a function to create the correct format. I figure this can serve as a nice way to integrate with taskwiki style stuff as well.

**Comment by linuxcaffe** [comment]
I think I found a clue! This vimrc config:
<pre>
let g:unite_taskwarrior_note_directory = '~/.task/notes'
</pre>
seems to be creating the note in;
<pre>
djp@tigger:~/.vim/bundle/unite-taskwarrior/~/.task/notes/b6a77620.tasknote.wiki  
or
djp@tigger:~/.task/wiki/~/.task/notes/b12ad853.tasknote.wiki 
</pre>
seeming dependent on the PWD when the note was created.. which is not what I expected!

**Comment by blakesweeney** [comment]
Huh, that's odd. I'll fix it once I figure out what is causing that.

**Comment by linuxcaffe** [comment]
all working as advertised!

**Comment by linuxcaffe** [comment]
This feature, the insert-description-as-first-line-of-notefile thing, is working great, and it makes a huge difference to connect the task and the tasknote..

and I found something even better IF you're using taskwiki; insert a taskwiki-formatted task, #uuid and all, and then, when editing that tasknote, just hit <CR> to see the full task info, or '<leader>t m' to modify the task, and any external changes to the description or status, get propagated back to the tasknote. 

<pre> 
* [ ] write a description  #uuid-short  
</pre>

as the first line, would be super-great used with taskwiki, super-weird otherwise :)
