### ISSUE TITLE
open /projects and /tags in a vsplit

### ISSUE THREAD

**Issue by linuxcaffe** [blakesweeney/unite-taskwarrior#11]
Projects and tags reports tend to be long and narrow, ideal candidates for opening in a vsplit. 

Then, after selecting from that list of projects (or tags) generating a new set of tasks, does that vsplit close? I'm not sure..

**Comment by blakesweeney** [comment]
My preference is to leave that sort of configuration to users as unite already has a way of doing that. For example the vim command `:Unite taskwarrior/projects -vertical -winwidth=40`. Opens the project listing in a 40 character wide vertical split which is what you're after I think.

**Comment by linuxcaffe** [comment]
I tried these configs;
<pre>
nnoremap <silent> <Leader>Tw :Unite taskwarrior -winheight=50<CR>
nnoremap <silent> <Leader>TwProjects :Unite taskwarrior/projects -vertical -winwidth=40<CR>
nnoremap <silent> <Leader>TwTags :Unite taskwarrior/tags -vertical -winwidth=40<CR>
</pre>
and while the first one worked, the second two did not..

**Comment by blakesweeney** [comment]
Does doing `:Unite taskwarrior/projects -vertical -winwidth=40` work? And what did you see when the didn't work? Also, those are some seriously long key mappings, do you really mean to type `TwProjects` and not just `TwP` or something?

**Comment by linuxcaffe** [comment]
1) just issuing the command above works just fine
2) I guess I was (wrongly) thinking more "command" than "keymap", 
:TwP< tab >< CR >
, but you're totally right, just < leader >TwP is better!

**Comment by linuxcaffe** [comment]
I think this is looking like a personal use-case sort of thing, and I'm gonna re-read the README.md, and try the suggestions, and maybe re-open this issue later. thanks!
