### ISSUE TITLE
open tasknote file in a split window

### ISSUE THREAD

**Issue by linuxcaffe** [blakesweeney/unite-taskwarrior#12]
rather than opening the tasknote file in a separate buffer, it might be better to open in a window-split, with the task list still in sight.

**Comment by blakesweeney** [comment]
Opening in a split window is already possible using, standard unite actions. I have:

```vim
nnoremap <silent><buffer><expr> <C-v> unite#do_action('vsplit')
inoremap <silent><buffer><expr> <C-v> unite#do_action('vsplit')
```

in my `ftplugin/unite.vim`. If you don't want to use mappings, you can also hit `a` in normal mode and then get a listing of all possible actions, one of them is vsplit. I'm not sure about keeping the window open, I'll play around with it a bit.

**Comment by linuxcaffe** [comment]
this vsplit config option should make it's way into the docs
