### ISSUE TITLE
filter config not filtering 

### ISSUE THREAD

**Issue by linuxcaffe** [blakesweeney/unite-taskwarrior#13]
In my .vimrc
<pre>
let g:unite_taskwarrior_filter = 'status.not:deleted and status.not:completed'
</pre>
:Unite taskwarrior
still shows completed and deleted tasks

**Comment by blakesweeney** [comment]
Try doing: 

```vim
let g:unite_taskwarrior_filter = ['status.not:deleted',  'status.not:completed']
``` 
I ran in to some problems with quoting I think and found having an array for each term works more reliably. If that's not it I'll look some more.

**Comment by linuxcaffe** [comment]
bing! that does it!
