### ISSUE TITLE
< BkSpc > = a "back button"

### ISSUE THREAD

**Issue by linuxcaffe** [blakesweeney/unite-taskwarrior#14]
when changing reports, from one listing, to a tag list, to a project detail (info) display, I often find I'd like to return to the previous list, but then I have to re-envoke the sequence. 
A command-history and using the BACKSPACE key, might make that navigation easier (possible).

**Comment by linuxcaffe** [comment]
vimwiki also uses the BACKSPACE to back through link history.. for what it's worth ;-)

**Comment by blakesweeney** [comment]
The issue with this is that unite doesn't provide this functionality and I'm not sure it provides the information to make it possible. I don't know if it gives me enough information to know what source was opened with what options (vertical split, what filter, etc). I'll look into it, as I can see it's usefulness but I can't promise anything.

**Comment by blakesweeney** [comment]
So I've looked into this a bit and unite provides `:UniteResume` which opens the previous unite buffer. It opens everything exactly as it was which is great! Sadly, it does not work to open the previous if you already have one open so we can't reuse it. But unite does at least provide all the info so it should be possible to implement your request.

**Comment by blakesweeney** [comment]
I've made some progress on this issue. Take a look at the latest commit. This adds a previous action which will open up the previous unite buffer. Right now it only exists in the taskwarrior source (which I should fix I think). It seems to work ok for me. For some reason I can't add bindings for it within the plugin but if you add something like:

``` vim
nnoremap <silent><buffer><expr> <BS>  unite#do_action('previous')
```

to `ftplugin/unite.vim` you will be able to use backspace to go back. Let me know how it works for you.

**Comment by blakesweeney** [comment]
This is now mapped for the taskwarrior source. I will add it to all sources and that should take care of this issue.

**Comment by linuxcaffe** [comment]
wow!

**Comment by linuxcaffe** [comment]
good progress here, but in testing it, iI hit

<pre>
[unite.vim] function unite#action#do..367, line 3
[unite.vim] Vim(call):E716: Key not present in Dictionary: start.func(past[0])
[unite.vim] Error occurred while executing "previous" action!
</pre>

**Comment by blakesweeney** [comment]
What source did this happen in?

**Comment by linuxcaffe** [comment]
I don't remember, I'll try to reproduce..

**Comment by linuxcaffe** [comment]
happened again, from a tasklist, hit BkSpc

**Comment by linuxcaffe** [comment]
and from a /notes source, (and others) BkSpc throws 

<pre>
Error detected while processing function unite#action#do..<SNR>143_get_candidates_action_table..unite#util#print_error:
line    2:
E714: List required
E714: List required
</pre>

**Comment by blakesweeney** [comment]
I took a look at this and it seems to work for notes now. I've used it in most other sources and all seems to be well. Let me know if you run into this issue some more.

**Comment by linuxcaffe** [comment]
Much less annoying! thanks!
