### ISSUE TITLE
crashiness

### ISSUE THREAD

**Issue by linuxcaffe** [blakesweeney/unite-taskwarrior#17]
In trying to run "Unite taskwarrior" I get these errors and no list;

<pre>
function <SNR>21_call_unite_empty..unite#start..unite#start#standard..unite#candidates#_recache..<SNR>72_recache_candidates_loop..<SNR
>72_get_source_candidates..13..unite#taskwarrior#select..unite#taskwarrior#parse, line 3
Vim(let):E697: Missing end of List ']':
[unite.vim] Error occurred in gather_candidates!
[unite.vim] Source name is taskwarrior
</pre>

any idea how to get past?

**Comment by blakesweeney** [comment]
Looks like it is struggling to parse the output of taskwarrior. I'm guessing the output from taskwarrior is not exactly what vim can parse. Is this a recent version of dev? I tried to improve parsing by using an actual JSON parser and not just evaling the JSON string (since JSON and vimscript have the same syntax). It was working for me, but maybe I need a more robust parser.

**Comment by linuxcaffe** [comment]
oh wait.. it might just be that I'm using the current (2.4.5) taskwarrior build, which has some significant differences, not least of which json.array=on by default.

Because 2.4.5 (soon to be 2.5beta) is so dramatically changed (improved parser, some syntax changes) I might suggest that unite-taskwarrior chase that version.. y'know, for the future!

**Comment by blakesweeney** [comment]
That sounds good to me. It should make the parsing a bit easier if we are always getting a valid JSON array back. I'll set my config to have json.array=on  and develop against that.

**Comment by blakesweeney** [comment]
Hopefully this fixes the issue. Is there a mailing list of taskwarrior where the devs talk the format and such? It would make it easier for me to keep track of stuff like this.

**Comment by linuxcaffe** [comment]
That's great, I'll try it and report back.
the devs from around the globe and around the clock can be found on irc.freenode.net #taskwarrior

**Comment by linuxcaffe** [comment]
sad to say, still crashy..

<pre>
function <SNR>21_call_unite_empty..unite#start..unite#start#standard..unite#candidates#_recache..<SNR>90_recach
e_candidates_loop..<SNR>90_get_source_candidates..57..unite#taskwarrior#select..unite#taskwarrior#defaults, lin
e 9
Vim(let):E730: using List as a String
[unite.vim] Error occurred in gather_candidates!
[unite.vim] Source name is taskwarrior
</pre>

**Comment by blakesweeney** [comment]
Ok I fixed that issue as well. Also, if you could show the output from `task export` for one task that would be great.

**Comment by linuxcaffe** [comment]
here's one; https://gist.github.com/adbf078401055530a70d

**Comment by linuxcaffe** [comment]
Yay! Works! and looks great! Let the new-feature-testing begin!

**Comment by blakesweeney** [comment]
Great! Let me know how those go.

**Comment by linuxcaffe** [comment]
working great, error free, closing this issue!
