### ISSUE TITLE
annotation indentation under desription

### ISSUE THREAD

**Issue by linuxcaffe** [blakesweeney/unite-taskwarrior#19]
(also applies to g:unite_taskwarrior_projects_padding=#_of_spaces  etc.)

I really like the vertical lists for tags and projects, but I think they are using more screen real-estate than necessary. This issue is about tighter vertical project and tag lists. Currently, at a width of 40, it looks like 20 leading spaces, maybe 20 between tag and #, and then another 8(?) trailing.

g:unite_taskwarrior_tag_padding=1

would be my preferred default.

A related factor is how the tags display collapses to " .. " if there isn't enough width for the widest tag-row, It would be much better if only the tag-rows that exceed the available width, were truncated.

this also applies to projects etc.

**Comment by blakesweeney** [comment]
Yeah the formatting is not great right now. I'd like to make it smart enough so that it will only take as much room as needed for each project/tag name. This should help with this display issue.

**Comment by linuxcaffe** [comment]
this specific formatting issue has gone away

**Comment by linuxcaffe** [comment]
this issue is back! :)

I think it's obvious that annotations will really only be helpful when they are indented under description, so I'm re-opening. This doesn't have to have anything to do with taskwarrior indent settings, but it could. Those are obtainable with 'task  _get rc.indent.annotation' (defaults to 2)

**Comment by blakesweeney** [comment]
So they are indented now, but the are indented under the start of the line so:

```
- [ ] Some task
  An annotation
```

Do you think it should be:

```
- [ ] Some task
       An annotation
```

instead? In the second example we add a leading 4 or so spaces for the leading `- [ ]` that is part of every task?

For the moment I will just use 2 for the indenting, but once I write the code for the settings source I will make it use the configuration for taskwarrior.

**Comment by linuxcaffe** [comment]
yes, yes, just like example 2 will greatly reduce the "visual noise" of annotations, and if that can (eventually) be driven by taswarrior config, all the better!

**Comment by blakesweeney** [comment]
Ok this should be fixed now. It should be 2 under the description. After adding the settings source I'll have this be configured to make taskwarrior.
