### ISSUE TITLE
Unite taskwarrior/contexts

### ISSUE THREAD

**Issue by linuxcaffe** [blakesweeney/unite-taskwarrior#20]
To produce a list of defined contexts (context list) then provide available actions, to add, edit or open a tasklist filtered by the selected context. 

Unlike the 'task context foo' command, the context=foo is not set in .taskrc. 
Calling 'Unite taskwarrior/context foo' would filter by the foo context definition for one-shot, because otherwise it would affect all other local instances of tw.

**Comment by blakesweeney** [comment]
I have a branch where this is possible. There are a couple rough edges at the moment, but I'll clean it up and make it available shortly.

**Comment by blakesweeney** [comment]
Try out the latest updates. This provides a way to list contexts and the like. At the moment it does not provide the filtering you've mentioned, but this should be a nice start.

**Comment by linuxcaffe** [comment]
It's excellent! really handy! thanks!
