### ISSUE TITLE
new option g:unite_taskwarrior_rollover=yes/no

### ISSUE THREAD

**Issue by linuxcaffe** [blakesweeney/unite-taskwarrior#21]
Currently, a listing will "roll over" from bottom-to-top, and this can be convenient, and it can be disorienting. Because this behavior would be a personal-preference thing, having it as optional would be better.

**Comment by blakesweeney** [comment]
This is a unite.vim feature. I'll see if unite lets you control this, but nothing stands out after a quick look at the docs. Might have to open an issue for unite.vim.

**Comment by blakesweeney** [comment]
I've looked over the docs and there doesn't seem to be a variable for this. I would suggest you open an issue with unite.vim https://github.com/Shougo/unite.vim/issues. Shougo is pretty responsive. As this isn't something that utw can control I'm going to close the issue.
