### ISSUE TITLE
:Unite taskwarrior/notes

### ISSUE THREAD

**Issue by linuxcaffe** [blakesweeney/unite-taskwarrior#22]
A new command that generates a list of uuid.tasknote.ext files found in the note-directory
Displaying the filename and the first line of each tasknote, making it easiy to select from an otherwise meaningless list of UUID.ext.ext files.

**Comment by blakesweeney** [comment]
This seems pretty straight forward to do. I'd probably write another source `Unite taskwarrior/notes` which does what you suggest. Probably with actions like: open, preview, and delete.

**Comment by blakesweeney** [comment]
Try out the latest version. I've added a notes source which should do what you want. The only thing to note is that this plugin does not delete notes files by itself meaning your notes will include finished stuff. I'm not planning on adding features to cleanup the files since it's pretty normal to change task status outside this plugin.

**Comment by linuxcaffe** [comment]
That's the idea! Awesome! .. but .. ;-)  (there's always a "but")

The path/filename is overkill (but showing the description is essential) so, if the first line of the tasknote is _always_ the description, then one-line-per-tasknote shoulld be fine.

**Comment by blakesweeney** [comment]
That's a good point. I'll take care of that later.

**Comment by linuxcaffe** [comment]
I had an idea for a really nifty enhancement for taskwarrior/notes; Imagine if you will that the command opened a window with a 50/50 vertical split. On the left is the list of notefile first-lines, almost as it is now, but on the right is a preview of the file at the top of the list. As you cursor down over the list (on the left) the file preview on the right is refreshed, allowing the user to browse the contents of all the notefiles very quickly.

**Comment by blakesweeney** [comment]
This is nearly possible right now. If you try: `:Unite taskwarrior/notes -auto-preview -vertical` it will show the notes in a vertical split with a small preview window above. As you move along the candidate list it will preview. It does leave the current buffer visible, which may not be what you want but is pretty close I think. I don't quite know the right settings to get exactly what you want but this is pretty good.

Also, you can toggle this behavior. If you add:

``` vim
nmap <buffer> <C-j>     <Plug>(unite_toggle_auto_preview)
```

to your unite settings then you can toggle this behavior in any unite source.

**Comment by linuxcaffe** [comment]
Aw man that's awesome! almost exactly what I was on about :)

Leaving the other buffer is not the end of the world, but maybe sub-optimal, and is there an easy way to split it so the first-line-list is on the left, and the preview on the right?

**Comment by blakesweeney** [comment]
Ok, I think doing:

`:Unite taskwarrior/notes -auto-preview -vertical-preview -no-split`

does exactly what you want. This will have a preview split vertically that shows automatically and will replace the current buffer with the unite windows. Doing that has some limitations, you should see `:help unite-options-no-split` for details on that.

**Comment by linuxcaffe** [comment]
that is soooo close! and that :help file is eye-opening! however, I didn't see a way to reverse the windows, left-and-right, because then it would be _perfect_! .. ok, without the path/filename lines.. but _then_ it would be perfect! ;-)

**Comment by blakesweeney** [comment]
Try the `set splitright` in your vimrc. It will open notes to the right. The pathnames and such should be removed in the latest commits. Right now it should only display the header line of each file.

**Comment by linuxcaffe** [comment]
splitright worked like a charm, but I'm still seeing the path/filename line..

**Comment by linuxcaffe** [comment]
I take it all back, it ALL workslikeacharm!

**Comment by linuxcaffe** [comment]
I might highly recommend adding this as a default mapping;

<pre>
nnoremap < silent >  < Leader >Tn :Unite taskwarrior/notes -auto-preview -vertical-preview -no-split< CR n >
(note: extra spaces added so the stupid githib thing will parse)
</pre>

can the splitright be added to that, instead of separate vimrc config?

**Comment by blakesweeney** [comment]
I'm going to start collection mappings like this in the wiki and link to them in the readme. Feel free to suggest whatever you think would be a good addition there.

**Comment by linuxcaffe** [comment]
perfect! I'll share any cute configs I come up with, and maybe a screenshot or two.
