### ISSUE TITLE
on creating tasknote, add tag:note to task

### ISSUE THREAD

**Issue by linuxcaffe** [blakesweeney/unite-taskwarrior#23]
This would be the only clue that a task has a tasknote.

**Comment by linuxcaffe** [comment]
I gotta say, tasknotes are inherently problematic :) eventually, some routine to keep tag:note and tasknote "in sync" would be great, so every task that had an associated tasknote had a tag:note.

**Comment by blakesweeney** [comment]
That's a good point. I'll see what can be done on that front.

**Comment by blakesweeney** [comment]
This should be fixed. Now whenever opening a note it will add a +note to that note. This will not add the +note to things that already have notes however.

**Comment by linuxcaffe** [comment]
all good! thank you!
