### ISSUE TITLE
reverse indentation for annotation/description

### ISSUE THREAD

**Issue by linuxcaffe** [blakesweeney/unite-taskwarrior#24]
Currently, in a task list, the right-hand, then annotation, then (indented from that) description, and this is a bit confusing.

I think annotations should be indented under descriptions, to make the relationship clearer.

**Comment by linuxcaffe** [comment]
It might be a good idea just to follow rc.indent.annotation= rc setting

**Comment by blakesweeney** [comment]
Yeah this needs work. The issue I was having was figuring out how much (if any) to indent the text to deal with the stuff that unite adds to left side automatically.

**Comment by linuxcaffe** [comment]
Initial utw format has been established, this specific formatting problem has gone away
