### ISSUE TITLE
:Unite taskwarrior/actions

### ISSUE THREAD

**Issue by linuxcaffe** [blakesweeney/unite-taskwarrior#25]
This is like a source for all available sources, like a meta-source, that functions as a main-menu for top-level actions available to unite-taskwarrior. (the number of features and functions is growing, this would make all of them discoverable)

**Comment by blakesweeney** [comment]
You can use unite's built in source source. Doing `:Unite source` will give a list of all possible sources. You can type in a name and it will filter by it. So entering taskwarrior will show what you're interested in. In fact, you can do `:Unite source -input=taskwarrior` and get a list of all taskwarrior sources. This could go into a command easily enough. Also, unite supports autocomplete so you can type `:Unite ta` and then hit `<Tab>` to start completing possible sources.

**Comment by linuxcaffe** [comment]
when I hit "Unite ta" I get a SCREENFUL of options! :) 

:Unite source -input=taskwarrior is a good start,, I've mapped it to < leader >T?, and maybe something like it might go into the docs or defaults.

**Comment by blakesweeney** [comment]
I'll put it in the docs, I'm not sure it's worth it's own source as it is built in to unite.

**Comment by linuxcaffe** [comment]
documented!
