### ISSUE TITLE
document how to use tasknotes

### ISSUE THREAD

**Issue by linuxcaffe** [blakesweeney/unite-taskwarrior#3]
Hi! I'm poking around with unite-taskwarrior.. and trying to like it ;-)

One (of many) question(s); how does one use the tasknote functionality?

**Comment by linuxcaffe** [comment]
I'm getting the hang of it, found the (right there) docs, and have the notes thing working, sort of, 
still not using my configurations, but it's most likely PEBKAC :)

**Comment by blakesweeney** [comment]
Hey thanks for looking. This is still a bit rough around the edges so any feedback is appreciated. I'll try to polish this up and fix a couple issues.

**Comment by linuxcaffe** [comment]
the docs now have all the clues needed
