### ISSUE TITLE
unite-taskwarrior testing

### ISSUE THREAD

**Issue by linuxcaffe** [blakesweeney/unite-taskwarrior#30]
With all of these fab new functions, at some point, it would be prudent to run some regular tests, to see if the code is behaving as expected. I don't know a lot about vimscript test suites, but I do know that taskwiki has implemented something along those lines.

**Comment by blakesweeney** [comment]
I agree. I have far to little test code. I'm working on adding more, but not quickly enough.

**Comment by linuxcaffe** [comment]
well there's no pressure of course, we do this for "fun". That said, having some tests in place will circumvent support problems later, and having the test infrastructure in place earlier than later would probably be easier.

**Comment by blakesweeney** [comment]
So I've got some tests running which is good. For some strange reason there is an extra task when running on travis ci vs running on my machine. Does tw ship with an example task or something?

**Comment by linuxcaffe** [comment]
..umm I don't _think_ task ships with any tasks, no.

**Comment by blakesweeney** [comment]
Well somehow I have 5 things when I export but the taskdata files which it should be using only have 4. I'm not sure where this is coming from quite yet.

**Comment by linuxcaffe** [comment]
well, this may be a dumb question, but what does the fifth thing look like?

**Comment by blakesweeney** [comment]
It's labeled 'This is a new task'. A pretty printed export (that includes the fields utw computes is:

``` json
  {
    "uri": "<task:d078fd9e-affd-4bc1-afb8-c84b3c379fb4>",
    "stopped": 1,
    "description": "This is a new task",
    "stop_time": "",
    "modified": "20150829T204614Z",
    "short": "d078fd9e",
    "id": 5,
    "entry": "20150829T204614Z",
    "depends": [],
    "started": 0,
    "start_time": "",
    "status": "pending",
    "annotations": [],
    "urgency": 0,
    "project": "",
    "tags": [],
    "note": "/home/travis/.task/note/d078fd9e.mkd",
    "uuid": "d078fd9e-affd-4bc1-afb8-c84b3c379fb4"
  }
```

**Comment by linuxcaffe** [comment]
and this task has a tasknote? or at least a link to one? that part is bizarre.
I'll inquire on IRC where that sample task is generated, and how to avoid it.

**Comment by blakesweeney** [comment]
The tasknote path is generated by utw, but yeah I don't get where that is being generated.

**Comment by linuxcaffe** [comment]
travis tests in place, has the sample-task problem been worked-around? close this one?

**Comment by blakesweeney** [comment]
I found the problem. It was a weird case where despite the fact the tests were being run as travis, I could not run rake while within the tests. Adding rake to the Gemfile has fixed this issue.
