### ISSUE TITLE
:Unite taskwarrior/settings

### ISSUE THREAD

**Issue by linuxcaffe** [blakesweeney/unite-taskwarrior#32]
This listing show all unite-taskwarrior configs, and their current values, Some indication of which are the defaults would be good, and actions could allow changes to the configs, etc.

This sort of becomes a Utw diagnostic, so if environment-variables were also shown, would be even gooder.

**Comment by linuxcaffe** [comment]
could also be called taskwarrior/configs

**Comment by blakesweeney** [comment]
This seems pretty reasonable. I'll add it to my todo list.

**Comment by blakesweeney** [comment]
Huh, so I just finished up this source. Or rather what I thought was this source. I accidentally created a source that manipulates taskwarrior settings, not utw settings. Whoops. I can add a source for the configuration of utw.

**Comment by linuxcaffe** [comment]
that's awesome :) not what I was thinking, but awesome!

I was actually saving this feature request for v1.1+, and I would have called it :Unite taskwarrior/show

**Comment by blakesweeney** [comment]
On Wed, Sep 16, 2015 at 09:03:55AM -0700, David J Patrick wrote:

> that's awesome :) not what I was thinking, but awesome!
> 
> I was actually saving this feature request for v1.1+, and I would have
> called it :Unite taskwarrior/show

That is probably a better name.

**Comment by blakesweeney** [comment]
There is now a config source which should do what you were after. Try it out and let me know. You can do `:Unite taskwarrior/config`.

**Comment by linuxcaffe** [comment]
This seems pretty charming, exactly what I was getting at! cool!
