### ISSUE TITLE
:Unite taskwarrior/tests

### ISSUE THREAD

**Issue by linuxcaffe** [blakesweeney/unite-taskwarrior#33]
Another utility, shows a listing of all Utw "it ..." statements. This report could have an auto-preview to show the test routine, and actions for edit or new.

**Comment by blakesweeney** [comment]
This isn't really in the scope of utw. This is meant to be a good way to interact with taskwarrior. Plus I'm not sure how useful this is. Doing `:Unite grep:t` will let you find all test definitions and adding new ones can be done easily by hand or snippets if desired.

**Comment by linuxcaffe** [comment]
ok! the inspect-and-edit tests wasn't really for me anyways :)

:Unite grep:t didn't do nuthin for me, but ask for "Pattern: ". I'll have to learn how unite grep works.
