### ISSUE TITLE
docs: expand unite format ducumentation

### ISSUE THREAD

**Issue by linuxcaffe** [blakesweeney/unite-taskwarrior#34]
It seems that unite format functionality is very powerful, but far from obvious. some more clues to how formats work, more examples and/or links to online docs, would be great, either in the helpfile, or the new wiki.

**Comment by linuxcaffe** [comment]
some links:
Beginner's Guide to Unite http://usevim.com/2013/06/19/unite/

but I suppose the canonical would be ":he unite"

**Comment by blakesweeney** [comment]
Formatting is a bit of mess now yeah. It's not clear what formats for what and how to extend it.

**Comment by linuxcaffe** [comment]
this issue is unnecessary, we'll document as we learn more about formatting possibilities
