### ISSUE TITLE
org-mode style tags display

### ISSUE THREAD

**Issue by linuxcaffe** [blakesweeney/unite-taskwarrior#37]
If tags are important to your workflow (and I know they are) I would point to the way orgmode displays them;

<pre>
* [ ] task description to be ignored                                           :tag1:tag2:tag3:
</pre>

Tags are surrounded by colons (and multiples can share) and right-justified. The :tagone:tagtwo: format is also used by vimwiki, ledger-cli (unrelated, but I use it) and (obviously) by orgmode. This is just a display format, and has no affect on the actual tw tags.

Having the tags grouped like that, and right-justified, makes it very easy to compare tag-values for multiple tasks. 

An excellent example of such formatting in vim is the excellent (but no longer in development) vim-organizer, by the excellent Herb Sitz. https://github.com/hsitz/VimOrganizer . The clues to formatting tasks this way are buried somewhere in that code, and Mr Sitz is very helpful. see:https://vimeo.com/16650450 around the 5min mark, you can ignore most everything else :)

**Comment by linuxcaffe** [comment]
reviewing the video, I see vim-organizer used ":tagA::tagB::tagC:"  where imho should be ":tagA:tagB:tagC:".. it's just an idea :)

**Comment by blakesweeney** [comment]
I'm doing this on the branch mentioned in #36.

**Comment by linuxcaffe** [comment]
brilliant!
