### ISSUE TITLE
Use leading "-" or "+" for unite-taskwarrior tasklist format tasks

### ISSUE THREAD

**Issue by linuxcaffe** [blakesweeney/unite-taskwarrior#39]
Vimwiki ToDo syntax allows;

<pre>
* [ ] projectX       description, task starting with an asterisk     :test:
- [ ] projectY       description, task starting with a hyphen        :test:
+ [ ] projectZ       description, task starting with a plus sign     :test:
</pre>

interchangeably.

Taskwiki uses only the leading asterisk, and in recent discussion, tbabej (taskwiki author) shows no interest in using hyphen or plus sigh for anything.. and this is an opportunity!

If unite-taskwarrior uses a leading hyphen (- [ ]) for normal taslists, this can be one way to discriminate formats from taskwiki, and it will match vimwiki syntax highliting, and taskwiki won't ever try to process it.

As I suspect notefile handling will become one of utw"s "strong suits", using a leading plus-sign (+ [ ]) to indicate that the task has a notefile (perhaps in addition, or as an alternative to a +note tag) would be a very useful clue.

**Comment by blakesweeney** [comment]
Ok that seems reasonable to me. Right now it should show +note for new tasks that have notes. Adding a + to things with notes is easy enough. Do you think this should be triggered by the use_taskwiki setting? It is technically not a taskwiki task then.

Also, I'm pretty happy with the overall formatting so I'm going to merge it into develop. There are couple things left, like this and showing annotations, but overall I think it is good.

**Comment by blakesweeney** [comment]
Oh I misunderstood your comment, this will only apply when using the standard formatter. Very easy to do.

**Comment by blakesweeney** [comment]
One other idea I have had has been to indicate the active task with some sort of leading flag. In contexts, I use `>`. However here we could use something else. I think it might a good idea to mark an active task with `*`. I could also use that in contexts for consistency's sake as well.

**Comment by linuxcaffe** [comment]
interesting, taskwarrior default indicator for "started" is "+" so maybe THAT should represent +ACTIVE.

One more leading list character, that also matches vimwiki list syntax (see where I'm going?) is "#"

<pre>
# [ ] This task has a note, and number-sign has a nice notes mnemonic
</pre>

how about that?

**Comment by blakesweeney** [comment]
Yeah so maybe use `+` for active, `-` for normal `*` for notes, and then `#` for something else. That seems reasonable.

**Comment by linuxcaffe** [comment]
I'm wrong about the default tw active indicator;  it's "*". 
the defailt tw indicator for tag is "+"

The problem with "\* []" is that it is likely (almost certain) to conflict with taskwiki syntax. Maybe there's no conflict, I dont know, but I would be reticent.. you know better how bufftype stuff works..

I would lean towards  - normal, + note, # active -- for increasing visibility and no conflict

**Comment by linuxcaffe** [comment]
if we avoid \* [  ] altogether we can be sure that asterisk = taskwiki.

**Comment by blakesweeney** [comment]
That works for me. I've made that change. There won't be any conflict with taskwiki formatting in the unite buffer. At that level compatibility is mostly to make is easier on the user.

**Comment by linuxcaffe** [comment]
looks great!
