### ISSUE TITLE
document use of functions and variables

### ISSUE THREAD

**Issue by linuxcaffe** [blakesweeney/unite-taskwarrior#4]
Those functions in the help-file look so helpful! 
.. but some clues as to how to use them would be good!

and the variables in the help-file suggest a number of things, but I can't guess what they really might do.

please buff up the docs as though some of use are well-meaning idiots (because some of us are!)

thanks

**Comment by blakesweeney** [comment]
I've really increased the amount of docs. I haven't yet covered everything but if you could take a look and give any comments that will be great.

**Comment by linuxcaffe** [comment]
I most certainly will!
I'm out of town till wednesday, spotty connectivity, but really looking
forward to a better understanding. Thanks blake!

**Comment by linuxcaffe** [comment]
docs have caught up to current functionality
