### ISSUE TITLE
individual description truncation

### ISSUE THREAD

**Issue by linuxcaffe** [blakesweeney/unite-taskwarrior#44]
Currently, if any description in a utw#format task exceeds the available width, all desriptions are truncated, mid-line  While this is effective and the intent of the task is still decipherable, a per-description scheme would be better, truncating a description as needed, leaving the others unmolested.

**Comment by blakesweeney** [comment]
My intent was to truncate the descriptions but never the tags, as there will be plenty of room for descriptions generally. Could you send a screenshot, because when I look I see long descriptions getting truncated where the tags start on a per description basis.

**Comment by linuxcaffe** [comment]
Opening a tasklist with

<pre>
nnoremap <silent>  <Leader>T  :Unite taskwarrior -vertical-preview -auto-preview -no-split<CR> 
</pre>

and obviously, I need to work on my unite mappings!
the trainwreck: http://picpaste.com/Utw_tasklist-trunc-trainwreck-P0xPqLwf.png
I'm seeing a stripe of ".." truncation down the middle of the window, the the <80col line wrapping is a mess too. My impression (wild guess) is that the preview window is driving the width, as the lasklist opens up looking good (>80col) and on the first previewed note, the tasklist window crunches down to what you see in the screenshot.

**Comment by blakesweeney** [comment]
Yeah that's really not what I want to happen. I haven't done much with autopreview, so maybe that is messing something up? I'm not sure I'll play with it.

**Comment by blakesweeney** [comment]
I'm having trouble reproducing this issue. I tried and I found that even if the preview took up most of the space I didn't see any truncation. Though I could be doing something wrong. I've made some changes to the preview to make it more stable as I found some other issues with it.

**Comment by linuxcaffe** [comment]
yeah, looking good in basic tests, thanks
