### ISSUE TITLE
how can I alias :Unite taskwarrior to :tw ?

### ISSUE THREAD

**Issue by linuxcaffe** [blakesweeney/unite-taskwarrior#5]
(subject says it all)

**Comment by blakesweeney** [comment]
You should be able to do: `:command! Tw :Unite taskwarrior`. Note the upper case because all user defined commands in vim must start with uppercase. You may be able to get around this by using `:cabbrev` to make `tw` and abbreviation of `Tw`.

**Comment by linuxcaffe** [comment]
ok, sounds good.. would that be set in vimrc?
can't I just make tw an abbreviation of Unite taskwarrior?

would you mind showing me an example of what that vimrc setting would look like?

"TW" is problematic, in that it is used by vim-taskwarrior.

**Comment by blakesweeney** [comment]
Sadly, vim prevents users from creating lower case commands (as far as I know anyway). You could try using `Utw` as the command, at least its a mnemonic. 

To add such a command put 
```viml
command! Utw :Unite taskwarrior
``` 

into your vimrc file.

**Comment by linuxcaffe** [comment]
well then! ":Tw it is!
thanks for the help!

**Comment by linuxcaffe** [comment]
Ok.. that sorta worked.. 
<pre>
command! Tw :Unite taskwarrior
</pre> 
in my vimrc worked for the simple "Tw ", but for "Tw:@tom" complains of "E488: Trailing characters" 
whereas ":Unite taskwarrior:@Tom" generates a list.
I must be missing something..

**Comment by blakesweeney** [comment]
You'll need a fancier command, something that uses `<args>` I think. I'll look into this.

**Comment by blakesweeney** [comment]
So I've come up with a command that may be what you want. Try this out and see if it does what you expect. You'll need to add the following to your vimrc. 

``` vim
command! -nargs=* -range=0 Tw
      \ call s:call_taskwarrior(<q-args>)

function! s:call_taskwarrior(args) abort
  let source = ['taskwarrior']
  call extend(source, split(a:args))
  call unite#start([source])
endfunction
```

As an example you can do stuff like `:Tw` to get a standard listing. `:Tw @tag` to get a tasks with a specific tag, `:Tw $project` for a specific project, etc.

**Comment by linuxcaffe** [comment]
Bloody brilliant! works great! and the un-ragged listings look great too!

exclamation-mark
exclamation-mark

thanks blake!
djp

**Comment by linuxcaffe** [comment]
this little nugget deserves documentation
