### ISSUE TITLE
bug: < CR > from tasklist opens both notefile and info

### ISSUE THREAD

**Issue by linuxcaffe** [blakesweeney/unite-taskwarrior#50]
< CR > first opens a tasknote.wiki (the nearest, or the last previewed, it seems, doesn't have to be over a task with a tasknote!) THEN the info window opens in a split of the tasknote.wiki. CR again, to close the info, leaves the notefile open.

**Comment by linuxcaffe** [comment]
Perhaps the key problem is that -auto-preview of a tasklist is currently auto-previewing tasknotes, and that might be fixed with #49

**Comment by blakesweeney** [comment]
CR should do the default action, which is viewing the info. Preview shows the notes, which probably explains this behavior. I think you are correct in that making preview show the task info will fix this, or at least have clearer behavior.

**Comment by linuxcaffe** [comment]
fixed! thanks!
