### ISSUE TITLE
question: how do I filter tasklist?

### ISSUE THREAD

**Issue by linuxcaffe** [blakesweeney/unite-taskwarrior#52]
After playing with utw for a while, I still haven't stumbled on how to filter a list! I'm assuming it's possible, how is it done?

**Comment by blakesweeney** [comment]
If you enter insert mode in a task list you can type and it will filter stuff. The filtering is based on whatever the displayed text is.

**Comment by linuxcaffe** [comment]
wow, that explains a lot! thanks! (docs need a note about that, and/or a link to basic unite reference
