### ISSUE TITLE
bug: /notes and /annotations errors

### ISSUE THREAD

**Issue by linuxcaffe** [blakesweeney/unite-taskwarrior#54]
With the latest build, attempting to run :Unite taskwarrior/notes, I get these errors:

<pre>
[unite.vim] function <SNR>45_call_unite..unite#start..unite#start#standard..unite#candidates#_recache..<SNR>122_recache_candidates_loop..<SNR>122_g
et_source_candidates..283..unite#taskwarrior#notes#select..unite#taskwarrior#notes#tasks, line 2
[unite.vim] Vim(for):E714: List required
[unite.vim] Error occurred in gather_candidates!
[unite.vim] Source name is taskwarrior/notes
Press ENTER or type command to continue
</pre>

and after :Unite taskwarrior/annotations

<pre>

[unite.vim] function unite#action#do..545..unite#start_temporary..unite#start#temporary..unite#start#standard..unite#candidates#_recache..<SNR>122_
recache_candidates_loop..<SNR>122_get_source_candidates..259..unite#taskwarrior#annotations#groups, line 1
[unite.vim] Vim(let):E121: Undefined variable: filt
[unite.vim] Error occurred in gather_candidates!
[unite.vim] Source name is taskwarrior/annotations
</pre>

I guess these might be related?

**Comment by blakesweeney** [comment]
Yeah they were. Also, I changed notes so only note matched by the current filter are displayed. Notes also takes the same arguments as other taskwarrior sources.

**Comment by linuxcaffe** [comment]
this seems to be fixed. I still think the /annotations source is backwards, as in #35 .. but..
