### ISSUE TITLE
bug: errors after viewing info

### ISSUE THREAD

**Issue by linuxcaffe** [blakesweeney/unite-taskwarrior#55]
it wasn't a showstopper, but these messages flashed past after viewing a task info report;

<pre>
[unite.vim] function unite#action#do..489, line 2
[unite.vim] Vim:Interrupt
[unite.vim] Error occurred while executing "view" action!
</pre>

**Comment by blakesweeney** [comment]
Odd, I'll look into this.

**Comment by blakesweeney** [comment]
I've looked into it a bit and I can't seem to trigger this. Could you give more exact steps and possibly the entries you see `:messages`?

**Comment by linuxcaffe** [comment]
haven't seen it again, maybe just a momentary glitch!?
