### ISSUE TITLE
rename :Unite taskwarrior/settings --> :Unite taskwarrior/show

### ISSUE THREAD

**Issue by linuxcaffe** [blakesweeney/unite-taskwarrior#56]
The /settings source is almost a perfect analog to the 'task show' command, and so, should be re-named "/show", to follow the path-of-least-surprise.

**Comment by blakesweeney** [comment]
Yeah that makes sense.

**Comment by blakesweeney** [comment]
This should be fixed now.

**Comment by linuxcaffe** [comment]
perfectly!
