### ISSUE TITLE
use UUID-short for task notes

### ISSUE THREAD

**Issue by linuxcaffe** [blakesweeney/unite-taskwarrior#7]
The likelyhood of collision is _very_ small, and it does make files listings less noisy.

**Comment by blakesweeney** [comment]
Do you mean base64 encode it, or just take the first few (8?) characters? I agree it would make file listings cleaner.

**Comment by linuxcaffe** [comment]
the latter, the first block of characters, no fancy encoding needed here :)

**Comment by blakesweeney** [comment]
This is the current behavior. I know that #10 shows there is a problem with the full path, but at least the file name is correct. I'm closing this unless you have other comments.
