### ISSUE TITLE
vimrc configs not being recognized

### ISSUE THREAD

**Issue by linuxcaffe** [blakesweeney/unite-taskwarrior#8]
It might well be my bad syntax.
My Unite taskwarrior related configs are:
<pre>
command! Tw :Unite taskwarrior
let g:unite_taskwarrior_filter = 'status.not:delete and status.not:completed' 
call unite#custom#source('taskwarrior', 'matchers', 'matcher_fuzzy')    
call unite#custom#source('taskwarrior', 'sorters', 'sorter_rank') 
nnoremap <silent> <Leader>Tw :Unite taskwarrior -winheight=50<CR>
nnoremap <Leader>Twa :UniteTaskWarriorAdd<CR> 
vnoremap <silent> <Leader>Twa :B UniteTaskWarriorAdd<CR>
let g:unite_task_note_directory = '~/.task/notes'  
let g:unite_task_note_suffix = 'tasknote.wiki' 
</pre> 
but on creating a note, it is still using "mkd" as suffix, and putting the note in "note" not "notes".

**Comment by blakesweeney** [comment]
So the issue with this is that the docs are wrong. If you use `g:unite_taskwarrior_note_suffix` and `g:unite_taskwarrior_note_directory` it should work correctly.

**Comment by linuxcaffe** [comment]
this now works great!
thanks!
