### ISSUE TITLE
:Unite taskwarrior/projects errors

### ISSUE THREAD

**Issue by linuxcaffe** [blakesweeney/unite-taskwarrior#9]
Calling :Unite taskwarrior/projects results in
<pre>
function <SNR>47_call_unite_empty..unite#start..unite#start#standard..unite#candidates#_recache..<SNR>146_recache_candidates_loop..<SNR>146_get_
source_candidates..364..unite#taskwarrior#projects#select, line 1
Vim(let):E119: Not enough arguments for function: unite#taskwarrior#filter
[unite.vim] Error occurred in gather_candidates!
[unite.vim] Source name is taskwarrior/projects
Press ENTER or type command to continue
</pre>
and no project list 

This is also true for :Unite taskwarrior/tags

**Comment by blakesweeney** [comment]
This should be fixed now.

**Comment by linuxcaffe** [comment]
should be.. but isn't!
after pulling todays develop, restarting vim and all that. :Unite taskwarrior/tags results in:
<pre>
function <SNR>47_call_unite_empty..unite#start..unite#start#standard..unite#candidates#_recache..<SNR>135_recache_candidates_loop..<SNR>135_get_
source_candidates..365..unite#taskwarrior#tags#select, line 9                                                                                   
Vim(let):E713: Cannot use empty key for Dictionary                                                                                              
[unite.vim] Error occurred in gather_candidates!                                                                                                
[unite.vim] Source name is taskwarrior/tags                                                                                                     
Press ENTER or type command to continue     
</pre>

**Comment by linuxcaffe** [comment]
After recent updates, :Unite taskwarrior/projects works! 
but :Unite taskwarrior/tags does not (same errors as above)

**Comment by blakesweeney** [comment]
Huh. And I'm pretty sure I fixed tags first. Well I'll work on that a bit more

**Comment by linuxcaffe** [comment]
errors gone, functioning most excellent! dude!
